name: Deploy Frontend to Google Cloud Run

on:
  push:
    branches:
      - main
      - feat/frontend

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Frontend Image
        working-directory: frontend
        run: |
          gcloud builds submit --tag asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/globetrotter-images/globetrotter-frontend .

      - name: Deploy Frontend Service
        run: |
          gcloud run deploy globetrotter-frontend \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/globetrotter-images/globetrotter-frontend \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated \
            --port 3000  # Specify the port Next.js uses
            --set-env-vars NEXT_PUBLIC_API_URL=${{secrets.NEXT_PUBLIC_API_URL}}
